package temp.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import temp.entity.Member;
import temp.entity.MemberExample;

public interface MemberMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbggenerated  Wed Aug 05 22:48:43 CST 2015
	 */
	int countByExample(MemberExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbggenerated  Wed Aug 05 22:48:43 CST 2015
	 */
	int deleteByExample(MemberExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbggenerated  Wed Aug 05 22:48:43 CST 2015
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbggenerated  Wed Aug 05 22:48:43 CST 2015
	 */
	int insert(Member record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbggenerated  Wed Aug 05 22:48:43 CST 2015
	 */
	int insertSelective(Member record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbggenerated  Wed Aug 05 22:48:43 CST 2015
	 */
	List<Member> selectByExample(MemberExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbggenerated  Wed Aug 05 22:48:43 CST 2015
	 */
	Member selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbggenerated  Wed Aug 05 22:48:43 CST 2015
	 */
	int updateByExampleSelective(@Param("record") Member record,
			@Param("example") MemberExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbggenerated  Wed Aug 05 22:48:43 CST 2015
	 */
	int updateByExample(@Param("record") Member record,
			@Param("example") MemberExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbggenerated  Wed Aug 05 22:48:43 CST 2015
	 */
	int updateByPrimaryKeySelective(Member record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbggenerated  Wed Aug 05 22:48:43 CST 2015
	 */
	int updateByPrimaryKey(Member record);
}