package temp.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import temp.entity.Notes;
import temp.entity.NotesExample;

public interface NotesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notes
     *
     * @mbggenerated Wed Aug 05 22:48:43 CST 2015
     */
    int countByExample(NotesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notes
     *
     * @mbggenerated Wed Aug 05 22:48:43 CST 2015
     */
    int deleteByExample(NotesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notes
     *
     * @mbggenerated Wed Aug 05 22:48:43 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notes
     *
     * @mbggenerated Wed Aug 05 22:48:43 CST 2015
     */
    int insert(Notes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notes
     *
     * @mbggenerated Wed Aug 05 22:48:43 CST 2015
     */
    int insertSelective(Notes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notes
     *
     * @mbggenerated Wed Aug 05 22:48:43 CST 2015
     */
    List<Notes> selectByExample(NotesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notes
     *
     * @mbggenerated Wed Aug 05 22:48:43 CST 2015
     */
    Notes selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notes
     *
     * @mbggenerated Wed Aug 05 22:48:43 CST 2015
     */
    int updateByExampleSelective(@Param("record") Notes record, @Param("example") NotesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notes
     *
     * @mbggenerated Wed Aug 05 22:48:43 CST 2015
     */
    int updateByExample(@Param("record") Notes record, @Param("example") NotesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notes
     *
     * @mbggenerated Wed Aug 05 22:48:43 CST 2015
     */
    int updateByPrimaryKeySelective(Notes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notes
     *
     * @mbggenerated Wed Aug 05 22:48:43 CST 2015
     */
    int updateByPrimaryKey(Notes record);
}